group_name: # group name as in srdf, updated by lbr_move_group.launch.py
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.01
